name: Build executable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconsole --icon assets/moct.ico --name moct --onefile --uac-admin main.py

      - name: Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: dist/moct.exe

      - name: Upload built executable
        uses: actions/upload-artifact@v4
        with:
          name: moct
          path: dist/moct.exe
